samvera/active_fedora

lib/active_fedora/indexing.rb
spec/integration/indexing_spec.rb
spec/unit/base_spec.rb

Because they don't have parsable graphs.

reindex_everything should ignore non-RDF sources

---

lib/generators/active_fedora/config/fedora/fedora_generator.rb

Otherwise it's trying to call ActiveFedora::File.expand_path
which is not a method

Use the File class in the root namespace

---

lib/active_fedora/attributes.rb
spec/unit/property_predicate_spec.rb

Warn when the same predicate is used in more than one property

---

lib/active_fedora/loadable_from_json.rb
spec/integration/solr_instance_loader_spec.rb

Previously only the first character of singular datastream attributes
was being returned when the object was loaded from solr.

Load singular datastream attributes from solr

---

lib/active_fedora/core.rb
spec/unit/core_spec.rb

correctly when the base_path setting in fedora.yaml was not set.
Takes care of https://github.com/projecthydra/active_fedora/issues/657
Note: When I removed the base_path from config/fedora.yml and ran all tests I got 20+ failing tests. I spot checked several of them and the issues where because the tests were hard-coded to expect a /test/ on the URL or because the cleaner didn't know how to clean from fedora/rest rather than fedora/rest/test. I didn't think this should be an issue with the code given the new tests that evaluate the new changes.

Fixes bug that prevented ActiveFedora from deserializing classes 

---

lib/active_fedora/file.rb
spec/unit/file_spec.rb

Encodes file name in HTTP header to allow for special characters in filename

---

lib/active_fedora/attached_files.rb
spec/unit/attached_files_spec.rb

This gives a helpful migration path instead of an error when add_file is
called with 3 or 4 arguments instead of the expected 2

Deprecate the three and four arg constructor to add_file

---

lib/active_fedora/associations/builder/contains.rb
lib/active_fedora/file.rb
lib/active_fedora/loadable_from_json.rb
spec/integration/attached_files_spec.rb

If a NonRDFSource has a parent which is an RDFSource (AF::Base) and the
parent indicates that it contains the file (ldp:contains) then there is
no need to send a HEAD request to see if the file exists.

Avoid unnecessary HEAD request on file retrieval. Fixes #493

---

lib/tasks/active_fedora_dev.rake

As of Jettywrapper 2.0.3, the hydra_jetty_version is no longer required unless you want to download a version of hydra-jetty other than master.

Jettywrapper doesn't require hydra_jetty_version

---

lib/active_fedora/relation/finder_methods.rb
spec/integration/solr_service_spec.rb

In preparation for a Hydra 8 release, this backport will allow the hydra gem to be on the latest rsolr without spewing a ton of deprecation warnings.  I tried to make this as similar to this commit (https://github.com/projecthydra/active_fedora/commit/75b4afb248ee61d9edb56911b2ef51f30f1ce17f) on the master branch while still keeping it contained and small.

Backport solr escape patch

---

lib/active_fedora/associations/builder/has_many.rb
spec/integration/associations_spec.rb

Fixes the bug demonstrated in [this gist](https://gist.github.com/mbklein/88d07b3fe6ad97ee5f1d), which I never got around to filing an issue about because I fixed it instead.

Allow a has_many association to specify an explicit foreign key via the :as option

---

active-fedora.gemspec
lib/active_fedora/associations/contains_association.rb
spec/spec_helper.rb
spec/unit/simple_datastream_spec.rb

This PR fixes an edge-case bug described in [@cjcolvar's gist](https://gist.github.com/cjcolvar/86f8c87f7be86c08fa62), in which loading a resource with a SimpleDatastream will fail if the resource's class hasn't been configured with a call to `#new` or `#create` yet.
The corresponding test has to set up the fixture via `Ldp::Orm` in order to prevent the test class from being configured during setup. Hence the ugly test. If there's a way to make it prettier, I'd welcome some feedback.

Make sure datastreams get configured on load as well as new/create

---

lib/active_fedora/attributes.rb
lib/active_fedora/attributes/property_builder.rb
lib/active_fedora/indexing.rb
lib/active_fedora/indexing/map.rb
lib/active_fedora/rdf/datastream_indexing.rb
lib/active_fedora/rdf/indexing_service.rb
lib/active_fedora/rdf/rdf_datastream.rb
spec/integration/attributes_spec.rb
spec/integration/field_to_solr_name_spec.rb
spec/integration/json_serialization_spec.rb
spec/integration/ntriples_datastream_spec.rb
spec/unit/base_active_model_spec.rb
spec/unit/ntriples_datastream_spec.rb
spec/unit/query_result_builder_spec.rb
spec/unit/rdf/indexing_service_spec.rb
spec/unit/rdf_resource_datastream_spec.rb
spec/unit/solr_query_builder_spec.rb

You should now add indexing hints to has_attributes by passing a block
similar to how you do it with rdf properties. e.g.:
```ruby
class Book < ActiveFedora::Base
has_metadata  'descMetadata', type: MODSDatastream
has_attributes :title, :license, datastream: 'descMetadata' do |index|
index.as :stored_searchable, :facetable
end
end
```

Move the indexing logic to the model. Fixes #736

---

lib/active_fedora/relation/finder_methods.rb
spec/integration/associations_spec.rb

For example, when loading a batch object it should be loaded into a Batch class (and not a File for example.)
Loading an object to the incorrect class could result in loss of data when saving the object back. For example, loading a File into a Batch and then saving the Batch will blow away all the properties of the File that were not present in the Batch (which would be the majority.)
The current version of the code still allows an object to be loaded into a parent class. For example, a BigFile object could be loaded into a File object as long as BigFile *is a subclass* of File. This could still result in loss of data but I wasn't sure I wanted to be too restrictive so I am leaving this open for now. We might want to prevent this altogether in the future.

Prevents an object from being loaded to the incorrect class. 

---

active-fedora.gemspec
lib/active_fedora.rb
lib/active_fedora/clean_connection.rb
lib/active_fedora/fedora.rb
lib/active_fedora/rdf/fcrepo4.rb
lib/active_fedora/rdf/ldp.rb
spec/integration/clean_connection_spec.rb

This is an LDP Connection that doesn't return server managed/LDP/AF added triples. Useful for returning what you put into LDP.

Clean Connection

---

lib/active_fedora/associations/collection_association.rb
spec/integration/collection_association_spec.rb

Previously a StackTooDeep was encountered in this situation

Raise an error when the inverse relationship can not be found.

---

lib/active_fedora/associations/has_and_belongs_to_many_association.rb
spec/integration/has_and_belongs_to_many_associations_spec.rb

previously we were getting:
```
ActiveFedora::UnknownAttributeError:
Item does not have an attribute `item_id'
```
if the inverse was a has_many.

Only set/save the inverse on a HABTM if the inverse is also HABTM

---

lib/active_fedora/file.rb

When trying to run specs for a gem that has `active-fedora` as a dependency, i was getting the following error:
```
.../gems/active-fedora-9.0.7/lib/active_fedora/file.rb:7:in `<class:File>': uninitialized constant ActiveFedora::File::Deprecation (NameError)
```
This change fixed it for me.

Requires 'deprecation' for ActiveFedora::File

---

lib/active_fedora.rb
lib/active_fedora/core.rb
lib/active_fedora/core/fedora_id_translator.rb
lib/active_fedora/core/fedora_uri_translator.rb
spec/unit/core/fedora_id_translator_spec.rb
spec/unit/core/fedora_uri_translator_spec.rb
spec/unit/core_spec.rb

They were sometimes nil before, which means other things can't rely on that
translator being there.

Make #translate_id_to_uri/uri_to_id reliable.

---

lib/active_fedora/attributes.rb
spec/unit/attributes_spec.rb

Trying to reduce/elimnate the useage of "datastream" especially in the
public API.

Use delegate_to instead of datastream in the options for property

---

lib/active_fedora.rb
lib/active_fedora/content_model.rb
lib/active_fedora/core.rb
lib/active_fedora/rdf/identifiable.rb
lib/active_fedora/relation/finder_methods.rb
spec/integration/datastreams_spec.rb
spec/unit/base_spec.rb
spec/unit/content_model_spec.rb
spec/unit/om_datastream_spec.rb
spec/unit/rdf_datastream_spec.rb
spec/unit/rdf_resource_datastream_spec.rb

See https://github.com/projecthydra/active_fedora/wiki/Patching-ActiveFedora-7.x-&-8.x-Casting-Behavior
for detailed information on the problem.
The solution offered in this patch preserves the most-specific-class algorithm
of `ActiveFedora::ContentModel.best_model_for` and raises a new execption,
`ActiveFedora::ModelNotAsserted` in `ActiveFedora::Core#adapt_to_cmodel`.
Note that a repository object can still be loaded into a model class not asserted,
for example, by using `.find` with `cast: false`.
Closes #746 (although not really a backport)

Patches casting behavior

---

lib/active_fedora/file.rb
lib/active_fedora/with_metadata.rb
spec/integration/with_metadata_spec.rb
spec/unit/file_spec.rb

Fixes #784
This parallels how ActiveRecord objects behave if there are no changes,
e.g.:
```
User.first.save
User Load (0.6ms)  SELECT  "users".* FROM "users"  ORDER BY
"users"."id" ASC LIMIT 1
(0.3ms)  begin transaction
(0.1ms)  commit transaction
=> true
```

File#save should return true if there is nothing to save

---

lib/active_fedora/associations/collection_association.rb
lib/active_fedora/associations/has_many_association.rb
spec/integration/has_many_associations_spec.rb

When a CollectionAssociation is loaded before the owing object is saved
the solr query is produced without the id of the owner, so all the
objects of the correct type are returned.
Ref #781

CollectionAssociation should generate a solr query lazily

---

lib/active_fedora.rb
lib/active_fedora/associations.rb
lib/active_fedora/associations/builder/directly_contains.rb
lib/active_fedora/associations/container_proxy.rb
lib/active_fedora/associations/contains_association.rb
lib/active_fedora/associations/directly_contains_association.rb
lib/active_fedora/autosave_association.rb
lib/active_fedora/base.rb
lib/active_fedora/containers/container.rb
lib/active_fedora/containers/direct_container.rb
lib/active_fedora/core.rb
lib/active_fedora/file.rb
lib/active_fedora/file_relation.rb
lib/active_fedora/identifiable.rb
lib/active_fedora/reflection.rb
lib/active_fedora/relation/finder_methods.rb
spec/integration/collection_association_spec.rb
spec/integration/complex_rdf_datastream_spec.rb
spec/integration/direct_container_spec.rb
spec/unit/files_hash_spec.rb

You can use the containers by calling:
```ruby
class FooHistory < ActiveFedora::Base
directly_contains :files, predicate:
::RDF::URI.new("http://example.com/hasFiles"), class_name: 'Thing'
end
```
if you don't specify a class_name it will default to ActiveFedora::File

Add direct containers

---

lib/active_fedora/identifiable.rb

mattr_accessor with a block sets the class variable when it's called.
If the value is customized and then Identifiable is included on another
class mattr_accessor resets the custom value to the default. This commit
prevents that overwriting.
See:
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/attribute_accessors.rb#L72
This supersedes #799

Translation procs should not overwrite one another

---

lib/active_fedora/loadable_from_json.rb
spec/unit/loadable_from_json_spec.rb

Fixes: 
```
NoMethodError:
undefined method `map' for
#<ActiveFedora::LoadableFromJson::SolrBackedResource::FakeQuery:0x007fee7f00b570>
```
as seen in https://github.com/projecthydra/sufia/pull/1149

A SolrBackedResource should be enumerable

---

lib/active_fedora/associations/contains_association.rb
lib/active_fedora/associations/indirectly_contains_association.rb
spec/integration/direct_container_spec.rb
spec/integration/indirect_container_spec.rb

This fixes the `RuntimeError: Couldn't find reflection` error
encountered in projecthydra-labs/activefedora-aggregation#36 #805

Direct/Indirect containers should have an include? method

---

active-fedora.gemspec
lib/active_fedora.rb
lib/active_fedora/base.rb
lib/active_fedora/indexers.rb
lib/active_fedora/indexers/global_indexer.rb
lib/active_fedora/indexers/null_indexer.rb
lib/active_fedora/schema.rb
lib/active_fedora/schema_indexing_strategy.rb
spec/integration/base_spec.rb
spec/integration/datastream_rdf_nested_attributes_spec.rb
spec/unit/indexers/global_indexer_spec.rb
spec/unit/rdf_resource_datastream_spec.rb
spec/unit/schema_indexing_strategy_spec.rb

Pending merge and release of ActiveTriples with Schema support.
This is related to https://github.com/ActiveTriples/ActiveTriples/pull/132 and I'm only doing it before that code is merged because I feel like there's discussion to have around this, especially in regard to the SolrApplicationStrategy.
I'm proposing that if you apply a schema you probably want it indexed, and by default the system should do that for you.

Add apply_schema support to AF.

---

lib/active_fedora/associations.rb
lib/active_fedora/associations/builder/directly_contains.rb
lib/active_fedora/associations/builder/directly_contains_one.rb
lib/active_fedora/associations/directly_contains_one_association.rb
lib/active_fedora/file.rb
lib/active_fedora/reflection.rb
spec/integration/directly_contains_one_association_spec.rb

Note: part of this functionality is blocked by #794

(Needs Review) implements directly_contains_one association

---

lib/active_fedora/associations/builder/has_and_belongs_to_many.rb
lib/active_fedora/associations/has_and_belongs_to_many_association.rb
spec/unit/has_and_belongs_to_many_association_spec.rb

Removes the unnecessary calls to :solr_page_size and takes advantage of
ActiveFedora::Base.find accepting an array. The method is also made
private.

Refactoring .find_target for HasAndBelongsToMany

---

lib/active_fedora/associations/collection_proxy.rb
spec/integration/relation_spec.rb
spec/unit/collection_proxy_spec.rb

Adds the .scope method to CollectionProxy so that you can chain
relations such as .limit to a CollectionProxy.

Return relation for .limit, fixes #352

---

lib/active_fedora.rb
lib/active_fedora/base.rb
lib/active_fedora/pathing.rb
lib/active_fedora/persistence.rb
spec/unit/pathing_spec.rb

This is based on some needs I've seen recently. I've seen PCDM examples prefix classes with names in the url, ex.
```
/works/work1
/works/work2
```
`works` is just a basic container. You can specify a containing URI for your classes:
``` ruby
GenericWork < ActiveFedora::Base
uri_prefix "works"
end
```
Creating a new GenericWork will create a uri similar to:
`/fedora/rest/dev/works/ab/cd/ef/abcdef` depending on your id minting scheme.

Add optional prefix to resource URI

---

lib/active_fedora/associations/builder/has_and_belongs_to_many.rb

Defines a destroy method that's only calling super, therefore it's unnecessary. @jcoyne right?

Removing dead define_destroy_hook method

---

lib/active_fedora/persistence.rb

The line is already being done in the refresh method https://github.com/psu-stewardship/active_fedora/blob/remove_dead/lib/active_fedora/persistence.rb#L166

Removing unneeded line

---

lib/active_fedora/fedora_attributes.rb
lib/active_fedora/file.rb
lib/active_fedora/identifiable.rb
lib/active_fedora/with_metadata.rb

We also changed spacing and removed the internal persistence module since it did not make as much sense when we were including persistence.

Refactoring ActiveFedora::File to use ActiveFedora::Persistence

---

lib/active_fedora/file.rb
lib/active_fedora/file/attributes.rb
lib/active_fedora/file/streaming.rb

This splits out some of the code in ActiveFedora::File into relevant modules for better organization and to
make the File class overall lighter and more easy to read.

Reorganizing ActiveFedora:File code

---

lib/active_fedora/associations/builder/property.rb
lib/active_fedora/attributes.rb
lib/active_fedora/indexing/map.rb
lib/active_fedora/indexing_service.rb
lib/active_fedora/rdf.rb
lib/active_fedora/rdf/field_map.rb
lib/active_fedora/rdf/field_map_entry.rb
lib/active_fedora/rdf/indexing_service.rb
lib/active_fedora/rdf/rdf_datastream.rb
lib/active_fedora/reflection.rb
spec/integration/belongs_to_association_spec.rb
spec/unit/indexing_service_spec.rb
spec/unit/rdf/indexing_service_spec.rb
spec/unit/rdf_resource_datastream_spec.rb

Solrizing AF::Base objects and properties share common behaviors. This refactors both methods for indexing objects and properties into a common method: `solrize_rdf_assertions` which creates other classes that can be overridden if users wish to alter the ways in which their solr fields are created.
This also addresses #809 where objects can be indexed using their uris as the value.

RDF::IndexingService indexes objects & properties

---

lib/active_fedora/associations/rdf.rb
spec/integration/associations/rdf_spec.rb

If only one property has been defined for a predicate,
there's no reason to run a query to filter the results by class.
This avoids a call to solr that is unnecessary in most situations.

Avoid unnecessary solr query

---

lib/active_fedora/file.rb

The new_record? call used to cause an API call to fedora, which we are
now able to avoid.

Refactor File#== to avoid an unnecessary API call

---

lib/active_fedora/associations.rb
lib/active_fedora/associations/collection_association.rb
lib/active_fedora/associations/directly_contains_association.rb
lib/active_fedora/associations/indirectly_contains_association.rb
lib/active_fedora/file.rb
lib/active_fedora/persistence.rb
spec/integration/direct_container_spec.rb
spec/integration/directly_contains_one_association_spec.rb

Implements delete for direct containers.

---

lib/active_fedora/associations/association.rb
lib/active_fedora/associations/basic_contains_association.rb
lib/active_fedora/associations/directly_contains_one_association.rb
lib/active_fedora/file.rb
lib/active_fedora/reflection.rb
lib/active_fedora/simple_datastream.rb

Enables removing several TODOs about using `tap`

Allow File constructor to take a block.

---

lib/active_fedora/versionable.rb
spec/integration/directly_contains_one_association_spec.rb
spec/integration/versionable_spec.rb

This no longer does anything meaninful, so it has been removed to
prevent confusion.

Remove has_many_versions

---

lib/active_fedora/associations.rb
lib/active_fedora/associations/association.rb
lib/active_fedora/associations/builder/association.rb
lib/active_fedora/associations/builder/property.rb
lib/active_fedora/associations/null_validator.rb
spec/integration/associations_spec.rb
spec/unit/builder/has_and_belongs_to_many_spec.rb

This allows for a good interaction point for adding additional type validations
to associations.

Add type validator objects to associations.

---

lib/active_fedora/associations/rdf.rb
spec/integration/associations/rdf_spec.rb

previously setting nil or [nil] caused a stacktrace:
`undefined method 'each' for nil:NilClass`

RDF association ids setter should handle nil

---

lib/active_fedora/associations/collection_association.rb
spec/integration/collection_association_spec.rb

There's an alternative method that's described as working, but we'd have to
change the solr query used to find the objects (add an :fl parameter) to make this work, and I'm not
sure that's possible with how many different ways of finding there is.

Add collection#select using block syntax.

---

lib/active_fedora/associations/contained_finder.rb
lib/active_fedora/associations/indirectly_contains_association.rb
lib/active_fedora/fedora.rb
lib/active_fedora/inbound_relation_connection.rb
spec/integration/indirect_container_spec.rb

The InboundRelation prefer header was causing a 3-5x performance
penalty. We can get the same info from Solr anyway.
Reverts #796
Fixes #875

Stop using InboundRelationConnection

---

lib/active_fedora/change_set.rb
lib/active_fedora/sparql_insert.rb
spec/integration/nested_hash_resources_spec.rb
spec/unit/change_set_spec.rb

This allows for nested resources without using blank nodes.

Enable support for hash URIs.

---

README.md

https://github.com/projecthydra/active_fedora/commit/5b6da6d141bf8cf2dca2e0948972019865ead28b introduces the use of Solr's TermsQParser which was introduced in Solr 4.10.  Earlier versions of Solr are not compatible.

Update README to reflect dependency on Solr 4.10

---

lib/active_fedora/file/attributes.rb
spec/unit/file_spec.rb

* Using new predicate (premis:hasMessageDigest) for file checksums
* Falling back on old predicate (fedora:digest) for backwards compatability
Fixes #883

Using premis:hasMessageDigest for checksum

---

active-fedora.gemspec

This enables catching 409 conflicts as Ldp::Conflict rather than
Ldp::HttpError.  This is necessary because Fcrepo 4.3 changed the error
code from 400 to 409 when you tried to modify a system property

Update ldp gem to 0.4.0.

---

lib/active_fedora/indexing_service.rb

This method was not called from outside of the object. This reduces
the outward facing API of the object.

Moving a method to protected

---

lib/active_fedora/file/attributes.rb
lib/active_fedora/fixity_service.rb
spec/unit/file_spec.rb

Fcrepo4.digest was used by Fedora < 4.2, but it was removed
from the 2015-07-24 version of the fedora 4 ontology
http://fedora.info/definitions/v4/2015/07/24/repository
and from rdf-vocab in version 0.8.5

Don't use Fcrepo digest predicate from rdf-vocab

---

lib/active_fedora/nested_attributes.rb
spec/integration/nested_attribute_spec.rb

Nested attributes was previously skiping the check of the reject_if proc
if the _destroy flag was passed. This was occuring when allow_destroy
was false, so the record was getting updated. Thanks to @ojlyytinen for
finding this bug and the orignal work on PR #879 from which this PR is
inspired.

Don't skip reject_if when _destroy is passed

---

lib/active_fedora.rb
lib/active_fedora/association_hash.rb
lib/active_fedora/associations.rb
lib/active_fedora/associations/basic_contains_association.rb
lib/active_fedora/associations/builder/contains.rb
lib/active_fedora/associations/id_composite.rb
lib/active_fedora/core.rb
lib/active_fedora/errors.rb
lib/active_fedora/file.rb
lib/active_fedora/files_hash.rb
lib/active_fedora/persistence.rb
lib/active_fedora/reflection.rb
spec/integration/contains_association_spec.rb
spec/unit/attached_files_spec.rb
spec/unit/file_spec.rb

I'll squash this when it's okay - for now it shows a refactor route.

Allow for sub RDF Sources via contains

---

lib/active_fedora/fixity_service.rb
spec/unit/fixity_service_spec.rb

The fixity predicates have changed. We'll need to release a new version of AF once this is merged, but it requires an update to hydra-jetty.

Support both Fedora and Premis predicates, supports Fedora 4.4

---

lib/active_fedora/relation/calculations.rb
lib/active_fedora/relation/finder_methods.rb
lib/active_fedora/relation/query_methods.rb
lib/active_fedora/solr_query_builder.rb
lib/active_fedora/solr_service.rb
spec/integration/scoped_query_spec.rb
spec/unit/finder_methods_spec.rb
spec/unit/query_spec.rb
spec/unit/solr_config_options_spec.rb

Previously querying for a field to be nil (e.g. library_id: nil) would
just ignore that restriction and return all records. Now it actually
queryies for records that don't have library_id set (e.g. `-library_id:[*
TO *]`) Fixes #910

query for nil creates correct query

---

lib/active_fedora.rb
lib/active_fedora/checksum.rb
lib/active_fedora/file.rb
spec/unit/checksum_spec.rb
spec/unit/file_spec.rb

Adds `#checksum` method to ActiveFedora::File.

Adds ActiveFedora::Checksum class to encapsulate file digest info.

---

.rubocop.yml
lib/active_fedora/association_hash.rb
lib/active_fedora/attached_files.rb
lib/active_fedora/indexing_service.rb
spec/integration/persistence_spec.rb
spec/unit/attached_files_spec.rb
spec/unit/indexing_spec.rb

Previously AF was loading contained objects just to see if they had
changed or to save them.  This was unnecessary and costly.
Fixes #927 and Fixes #928

Avoid unnecessary loads

---

lib/active_fedora/datastreams/nokogiri_datastreams.rb
lib/active_fedora/file.rb
spec/unit/attributes_spec.rb

Create failing test for issue with datastreams resetting to old version after save related to https://github.com/projecthydra/active_fedora/issues/913
lib/active_fedora/file.rb#refresh resets @ds_content
lib/active_fedora/datastreams/nokogiri_datastream.rb#remote_content change @datastream_content to @ds_content
Closes #913
Fixes an issue where xml datastreams were reverting to the old version after and edit and save.

Fix issue where xml datastreams reverting after save, closes #913

---

lib/active_fedora/indexing_service.rb
lib/active_fedora/loadable_from_json.rb
lib/active_fedora/querying.rb
lib/active_fedora/solr_instance_loader.rb
spec/integration/solr_instance_loader_spec.rb

Fixes #905. Trying to access create_date or modified_date in objects loaded from Solr used to raise an error. They are now loaded properly from the Solr properties system_create and system_modified.

Load create_date and modified_date from Solr.

---

lib/active_fedora.rb
lib/active_fedora/loadable_from_json.rb
spec/integration/date_time_properties_spec.rb

As it stands, time zone information is not stored in Fedora, instead it's just always set to Z. All time information is effectively shifted by your local time offset if you take time zones into account. This results in unexpected behaviour where timestamps for example end up in the future if your local time zone offset is positive.
```ruby
class Foo < ActiveFedora::Base
property :date, predicate: ::RDF::DC.date do |index|
index.type :date
end
end
foo = Foo.create(date: [DateTime.now])
sleep 1
foo.date.first > DateTime.now # => true assuming your time offset is positive
```
There seems to be a bug in RDF::Literal::DateTime#to_s which prints out time zone as Z if you initialise the object with a DateTime rather than a String, so this should be fixed there. But a similar bug is present also …

Save time zone information for DateTimes. Solr returns DateTimes rather than Strings.

---

lib/active_fedora/association_hash.rb
spec/unit/association_hash_spec.rb

Fixes #908
Adds unit tests for AF::AssociationHash.

Makes `has_key?` and `key?` behave consistently in AF::AssociationHash

---

lib/active_fedora/associations/indirectly_contains_association.rb
spec/integration/indirect_container_spec.rb

Fixes an issue with duplicate IDs being indexed the first time an object
is saved.

ids_reader should not return duplicates.

---

lib/active_fedora/fedora_attributes.rb

We were getting an error in our project build:
NameError: uninitialized constant RDF::Vocab
/home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/active_fedora-f85b4eab16f4/lib/active_fedora/fedora_attributes.rb:14:in `block in <module:FedoraAttributes>'

Adds explicit require of 'rdf/vocab' to AF::FedoraAttributes

---

lib/active_fedora/loadable_from_json.rb
spec/integration/date_time_properties_spec.rb

I'm getting `invalid date` when I have a date property that's empty: `''`
Not sure if this is a valid use case or not, but I'm getting it in the context of a Sufia app. Maybe I need to rectify this at the form/presenter level instead? Otherwise, here's the PR...

Don't try to parse empty dates

---

lib/active_fedora/persistence.rb
spec/integration/gone_spec.rb

We are running into instances where our minter is minting ids that have been deleted.  I would like access to the gone method here https://github.com/psu-stewardship/active_fedora-noid/blob/master/lib/active_fedora/noid/synchronized_minter.rb#L16
This way we will not create invalid ids and end up with an LDP::Gone exception when we try to save.

Allowing access to the gone? method from outside the object

---

lib/active_fedora/versionable.rb
spec/integration/versionable_spec.rb

Includes some refactoring, but the change in the spec test makes AF compatible with Fedora 4.5.

The jcr/mix versionable predicate is no longer used

---

lib/active_fedora/indexing/map.rb
lib/active_fedora/rdf/field_map.rb
spec/integration/rdf_nested_attributes_spec.rb

Allows you to configure how we index properties that are ActiveFedora::Base objects. Instead of using only the uri as the value of the solr field, you can specify any arbitrary property you want.
@jcoyne @tpendragon I'm curious as to what your thoughts are on this approach.

Pass hash of options to index.as

---

.gitignore
active-fedora.gemspec
config/fedora.yml
config/jetty.yml
config/solr.yml
lib/active_fedora/version.rb
lib/generators/active_fedora/config/fedora/templates/fedora.yml
lib/generators/active_fedora/config/solr/templates/solr.yml
lib/tasks/active_fedora_dev.rake

This puts development on ports 8983 and 8984 for Solr and Fcrepo respecively.  The test instances would be on 8985 and 8986 respectively.

Run test FCRepo on a separate instance from development

---

lib/generators/active_fedora/config/solr/templates/solr/config/solrconfig.xml
solr/config/solrconfig.xml

When this happens, facets only show the first 10 values and don't give
any indication that there is more than 10 (the more >>) link.  This will
allow users to customize a sensible limit in their Blacklight
Configuration

Don't default facet.limit

---

lib/active_fedora/config.rb
lib/active_fedora/fedora.rb
spec/fixtures/rails_root/config/fedora.yml
spec/unit/config_spec.rb
spec/unit/fedora_spec.rb

Faraday may require SSL options to work properly.  New code reads
optional :ssl key in fedora.yml, expecting one or two subkeys, :verify
and :ca_path.  If SSL options are present in the config, they are passed
to the Faraday connection contructor. See the Faraday docs for details.

Adds SSL options to config (closes #985)

---

lib/active_fedora/file_configurator.rb
lib/active_fedora/relation/finder_methods.rb
lib/active_fedora/solr_service.rb
spec/unit/file_configurator_spec.rb
spec/unit/finder_methods_spec.rb
spec/unit/solr_service_spec.rb

Lets you configure which Solr request handlers are used for selects and updates by specifying select_path and update_path in solr.yml. This requires a patch in RSolr as well, a pull request for that is at rsolr/rsolr#116. Probably best to wait merging this until that's merged just in case something in there needs to be changed.
I've made this backwards compatible so that Active-Fedora doesn't depend on the new version of RSolr. With an older version of RSolr the custom request handlers simply will not work.

Add support for customizable Solr request handlers.

---

lib/active_fedora/rake_support.rb
lib/tasks/active_fedora_dev.rake

In your rake file add:
```ruby
require 'active_fedora/rake_support'
```
Then you can define a task using with_test_server. For example:
```ruby
task :ci do
with_test_server do
Rake::Task['spec'].invoke
end
end
```

Share the test server method with downstream apps

---

lib/active_fedora/rake_support.rb

If there is a solr configuration local to the current working directory
use them.  Otherwise use the defaults in ActiveFedora.

Use local configurations for solr

---

lib/generators/active_fedora/config/solr/templates/solr/config/solrconfig.xml
solr/config/solrconfig.xml

When we moved to Solr 5, we inadvertently removed the autocommit from
solr. Thus no commit is ever sent.

Restore autocommit in the update handler

---

lib/active_fedora.rb
lib/active_fedora/default_model_mapper.rb
lib/active_fedora/model.rb
lib/active_fedora/model_classifier.rb
lib/active_fedora/query_result_builder.rb
lib/active_fedora/relation/finder_methods.rb
spec/integration/bug_spec.rb
spec/unit/active_fedora_spec.rb
spec/unit/default_model_mapper_spec.rb
spec/unit/model_classifier_spec.rb
spec/unit/model_spec.rb
spec/unit/query_result_builder_spec.rb

This pull request extracts two new classes from formerly class-level methods:
- `ModelClassifier` - for turning strings into class instances, and choosing the "best" match from a list
- `DefaultModelMapper` - for extracting model mapping information from resources or solr documents
This is a start at providing a flexible way to select appropriate model classes from resource data (say, from a different Solr field, or more complex logic).

Unify type to model mapping code

---

lib/active_fedora/indexing.rb
spec/unit/indexing_spec.rb

Now we can set an indexer without having to override a class method.

Move indexer to a class attribute

---

lib/active_fedora/querying.rb
lib/active_fedora/relation/finder_methods.rb
lib/active_fedora/solr_instance_loader.rb
spec/integration/full_featured_model_spec.rb
spec/unit/finder_methods_spec.rb
spec/unit/query_spec.rb
spec/unit/solr_config_options_spec.rb

`find_with_conditions` and `find_in_batches` return Solr results, not class instances. Rename these methods (and provide appropriate deprecation warnings) to clarify the intent.

Rename find_with_conditions and find_in_batches to search_with_conditions and search_in_batches

---

active-fedora.gemspec

Previously we were pulling solrizer in as a transitive dependency of OM,
but ActiveFedora depends directly on Solrizer, so we should reflect that
in the gemspec.

ActiveFedora depends on Solrizer

---

lib/active_fedora/identifiable.rb
lib/active_fedora/relation.rb
lib/active_fedora/scoping.rb
lib/active_fedora/scoping/default.rb
lib/active_fedora/scoping/named.rb
spec/unit/scoping_spec.rb

These are used by GlobalID, which we should add in the future so we can
use ActiveFedora with ActiveJob

Add default scopes

---

.rubocop.yml
lib/active_fedora/associations/association.rb
lib/active_fedora/associations/collection_association.rb
lib/active_fedora/associations/collection_proxy.rb
lib/active_fedora/associations/has_many_association.rb
lib/active_fedora/autosave_association.rb
spec/integration/has_many_associations_spec.rb
spec/unit/has_many_association_spec.rb

If the owner is unsaved, it will get the NullScope, which always returns
zero.  Fixes #1008

Delegate count to the scope

---

lib/active_fedora/file.rb
lib/active_fedora/file/attributes.rb
lib/active_fedora/with_metadata/metadata_node.rb
spec/integration/attached_files_spec.rb
spec/integration/file_spec.rb
spec/integration/om_datastream_spec.rb
spec/unit/file_spec.rb

Squash and rebase of file_mime_types branch by @tpendragon

ActiveFedora::File.mime_type should be updatable

---

lib/active_fedora/relation/finder_methods.rb

Otherwise a LocalJumpError will result because search_in_batches expects
a block

Pass the block from find_in_batches to search_in_batches

---

spec/integration/versionable_spec.rb

* Updates test to not rely on presence of mix:versionable triple (being removed in Fedora 4.5.1)

Fedora 4.5.1-RC compatibility

---

lib/generators/active_fedora/config/solr/templates/solr/config/schema.xml

`units` is now `distanceUnits`
Mirrors https://github.com/projecthydra/sufia/pull/1820/files
Without this fix, Solr refuses to load the core, e.g.:
```
hydra-development:
org.apache.solr.common.SolrException:org.apache.solr.common.SolrException:
Could not load conf for core hydra-development: Can't load schema
/var/folders/6q/13dm9dcn1qx_gw9x66lhl7jc0000gq/T/solr-6.0.0/server/solr/hydra-development/conf/schema.xml:
Plugin Initializing failure for [schema.xml] fieldType
```

Update schema for Solr 6

---

lib/active_fedora/associations/collection_association.rb
lib/active_fedora/associations/has_and_belongs_to_many_association.rb
lib/active_fedora/associations/rdf.rb

By not destroying the entire graph every time performance grows linearly instead of in an exponential fashion. It still needs to be tested on a large scale ( > 1000 members) but for hasCollectionMember relationships of < 500 it goes from 1200 seconds to 192 in my test environment.

Update graph instead of destroying it

---

lib/active_fedora/solr_hit.rb
spec/integration/solr_hit_spec.rb

SolrHit#instantiate_with_json should create persisted objects

---

lib/active_fedora/ldp_cache.rb
spec/spec_helper.rb

If `ActiveFedora::Cleaner` breaks because it can't connect to a resource, allow it to fail and just log a message. It's possible the test doesn't need those connections and may pass without active connections to external resources.

Suppress AF::Cleaner errors when running the test suite

---

lib/active_fedora.rb
lib/active_fedora/fedora.rb
lib/active_fedora/initializing_connection.rb
spec/unit/active_fedora_spec.rb

This is an attempt to allow runtime configuration of Fedora by deferring blocking and potentially breaking requests until they are actually necessary.

Defer `init_base_path` until it is required

---

active-fedora.gemspec
lib/generators/active_fedora/config/fedora/fedora_generator.rb
lib/generators/active_fedora/config/fedora/templates/fcrepo_wrapper_test.yml
lib/generators/active_fedora/config/solr/solr_generator.rb
lib/generators/active_fedora/config/solr/templates/solr_wrapper_test.yml
spec/integration/generators/fedora_generator_spec.rb
spec/integration/generators/solr_generator_spec.rb

Added development dependency on rails in order to include test for solr & fedora (rails) generators.
Closes projecthydra/hydra-head#339

Have generators create wrapper config files for test

---

.rubocop.yml
lib/active_fedora/associations.rb
lib/active_fedora/associations/builder/aggregation.rb
lib/active_fedora/associations/builder/has_subresource.rb
lib/active_fedora/associations/has_subresource_association.rb
lib/active_fedora/attached_files.rb
lib/active_fedora/reflection.rb
spec/integration/attached_files_spec.rb
spec/integration/attributes_spec.rb
spec/integration/complex_rdf_datastream_spec.rb
spec/integration/file_fixity_spec.rb
spec/integration/has_subresource_spec.rb
spec/integration/versionable_spec.rb
spec/unit/attached_files_spec.rb

`contains` is deprectated until AF 10. The plan is to add a true basic
containment, where I post to the BasicContainer to get a URI (rather
than knowing the relative path ahead of time).

Renamed `contains` to `has_subresource`

---

README.md
lib/active_fedora/file.rb
lib/active_fedora/file/attributes.rb
lib/active_fedora/with_metadata/default_schema.rb
lib/active_fedora/with_metadata/metadata_node.rb
spec/integration/file_spec.rb
spec/integration/om_datastream_spec.rb
spec/integration/with_metadata_spec.rb
spec/unit/file_spec.rb
spec/unit/with_metadata/default_metadata_class_factory_spec.rb

This unreverts a commit by @cjcolvar: https://github.com/projecthydra/active_fedora/pull/1035/commits/cd865dec0203ed79ad36c4b40d5dd7c2bd943d3c
Which was itself a squash and rebase of work that @tpendragon did.
Note that there are still two failing specs. Feel free to add commits to this branch and march this over the finish line. The two failures:
```
1) ActiveFedora::WithMetadata properties with defaults should respond to #has_mime_type
Failure/Error: it { is_expected.to respond_to(:has_mime_type) }
expected #<SampleFile uri="" > to respond to :has_mime_type
2) ActiveFedora::WithMetadata::DefaultMetadataClassFactory::build sets MetadataNode to the default schema using the default strategy
Failure/Error: expect(parent).to receive(:delegate).at_least(8).times
(Double …
```

ActiveFedora::File.mime_type should be updatable. Fixes #890, #1083

---

lib/active_fedora/file.rb
spec/unit/file_spec.rb

Previously metadata was only persisted when `save()` was called,
`save!()` was not persisting.

AF::File#save! should persist metadata

---

lib/active_fedora/file.rb
lib/active_fedora/om_datastream.rb
lib/active_fedora/rdf/datastream_indexing.rb

It's only used by RDF and om datastreams

Remove prefix method from File

---

lib/active_fedora/relation/finder_methods.rb
lib/active_fedora/scoping/named.rb
lib/active_fedora/solr_query_builder.rb
spec/integration/scoped_query_spec.rb
spec/unit/finder_methods_spec.rb
spec/unit/query_spec.rb

This allows for finding all the objects that are 'this OR that' instead of just 'this AND that'
Added parens around cluases since 'abc' AND  'ddd' OR 'fff' is not the same as 'abc' AND ('ddd' OR 'fff').  This was not an issue before since all the clauses were joined with AND

Adding the ability to join with OR from a where clause

---

lib/active_fedora/relation/finder_methods.rb
lib/active_fedora/scoping/named.rb
lib/active_fedora/solr_query_builder.rb
spec/integration/scoped_query_spec.rb
spec/unit/finder_methods_spec.rb
spec/unit/query_spec.rb

This allows for finding all the objects that are 'this OR that' which is how the active record where with an array works.
Added parens around clauses since 'abc' AND  'ddd' OR 'fff' is not the same as 'abc' AND ('ddd' OR 'fff').  This was not an issue before since all the clauses were joined with AND
This is an update for master that matches with the PR that was put into the 9.7.x branch and merged yesterday.

Sending multiple values from a where cluase will join with OR

---

lib/active_fedora/nom_datastream.rb
lib/active_fedora/om_datastream.rb
lib/active_fedora/rdf/ntriples_rdf_datastream.rb
lib/active_fedora/rdf/rdf_datastream.rb
spec/spec_helper.rb

Datastreams no longer need to be part of ActiveFedora. They are just ActiveFedora::Files.

Deprecate datastreams

---

.rubocop.yml
lib/active_fedora/associations/builder/orders.rb
lib/active_fedora/associations/orders_association.rb
lib/active_fedora/fedora_attributes.rb
lib/active_fedora/orders/list_node.rb
lib/active_fedora/orders/ordered_list.rb
lib/active_fedora/orders/target_proxy.rb
spec/unit/ordered_spec.rb

Shares an in-memory repository between the LDP graph and the AF::Base's
resource. Reduces graph copying by a significant amount.
Also adds an ids reader to ordered associations which doesn't instantiate objects.

Performance Improvements

---

lib/active_fedora/railtie.rb

Using the string arguments is now deprecated

Reference actual classes

---

active-fedora.gemspec

This is a meta gem. We don't want to foist all these dependencies on a user
This should eliminate problems like:
```
Your bundle requires gems that depend on each other, creating an
infinite loop.
Please remove either gem 'linkeddata' or gem 'rdf-vocab' and try again.
```

Remove linkeddata.

---

lib/generators/active_fedora/config/solr/templates/solr/config/solrconfig.xml

This PR is dependant on #1119 
Also adding in a few additional changes from Sufia that seemed reasonable
This change should fix the issue that some people have been seeing when running tests in other gems:
```
Failure/Error:
json = solr_connection.get 'terms', params: { 'terms.fl' => term,
```
The solr config that is currently generated by active fedora does not include the terms configuration.

Adding in the terms handler so that generated apps inculde this by default

---

active-fedora.gemspec

This is required to prevent an incompatible alignment of rubocop and
rubocop-rspec versions.  It should not be our job to notice this
(rubocop-rspec should use greater precision to describe the version(s)
of rubocop each release is compatible with), but in practice, it falls to
us.
Without this bump, the error upon running `rake` was:
```
Running RuboCop...
undefined method `for_all_cops' for #<Hash:0x007fac583619e0>
/Users/atz/.rvm/gems/ruby-2.3.0/gems/rubocop-0.42.0/lib/rubocop/config_loader.rb:119:in `merge_with_default'
...
```

Bump rubocop-rspec version

---

lib/active_fedora/core.rb

Instead of only Hashes. This allows ActionController::Parameters to work

Accept attributes that have the correct methods

---

active-fedora.gemspec

1.1.2 correctly solrizes the ActiveTriple::Relations that exist in AT 0.10

Bump dependency on rsolr to >= 1.1.2

---

lib/active_fedora/associations/collection_association.rb
lib/active_fedora/associations/contained_finder.rb
lib/active_fedora/core.rb
spec/unit/base_extra_spec.rb
spec/unit/core_spec.rb

to_class_uri was a poorly chosen name in light of the fact that it
doesn't return URIs.

Rename to_class_uri to to_rdf_representation

---

lib/active_fedora/rdf.rb
lib/active_fedora/rdf/field_map_entry.rb
lib/active_fedora/rdf/value_caster.rb
spec/unit/rdf/indexing_service_spec.rb

Temporary fix until we find a nicer way to index literal information.

Cast RDF Literals to strings when indexing.

---

lib/active_fedora.rb
lib/active_fedora/associations/collection_association.rb
lib/active_fedora/associations/has_and_belongs_to_many_association.rb
lib/active_fedora/attributes.rb
lib/active_fedora/cleaner.rb
lib/active_fedora/core.rb
lib/active_fedora/fedora.rb
lib/active_fedora/file_configurator.rb
lib/active_fedora/initializing_connection.rb
lib/active_fedora/loadable_from_json.rb
lib/active_fedora/model_classifier.rb
lib/active_fedora/null_logger.rb
lib/active_fedora/orders/ordered_list.rb
lib/active_fedora/relation/finder_methods.rb
lib/active_fedora/solr_hit.rb
spec/unit/core/logger_spec.rb

Use a null logging object, and now we'll hopefully never have to check `if ActiveFedora::Base.logger` ever again.

Use ActiveFedora::NullLogger

---

lib/active_fedora/file.rb

Grabbing Justin's fix and pushing it back to 9.7 as the old code caused large files to be read into memory directly.

Eliminate an unnecessary read of local content

---

lib/active_fedora/fedora.rb
lib/active_fedora/indexing.rb
spec/unit/base_spec.rb
spec/unit/core/fedora_id_translator_spec.rb
spec/unit/core/fedora_uri_translator_spec.rb
spec/unit/core_spec.rb
spec/unit/file_spec.rb

reindex_everything relies on id_to_uri('') to return the base uri which is undocumented and untested.  active_fedora-noid throws an exception when attempting to call id_to_uri with the empty string.  This PR adds a base_uri method to ActiveFedora.fedora and uses this in reindex_everything instead of id_to_uri.

Fix reindex_everything for use with active_fedora-noid

---

spec/integration/base_spec.rb
spec/unit/query_spec.rb

* Removing invalid namespaces from test ids that causes test failures in Fedora 4.7.1-RC-1

Removing invalid namespaces from tests

---

lib/active_fedora/null_logger.rb
spec/lib/active_fedora/null_logger_spec.rb

Adding the standard logging level questions:
* `#debug?`
* `#info?`
* `#warn?`
* `#error?`
* `#fatal?`
Closes #1184

Ensuring NullLogger responds to logging questions

---

lib/active_fedora.rb
lib/active_fedora/railtie.rb

Previously eagerloading was not occuring, and on a threaded server we
could see errors like this:
```
NameError: uninitialized constant ActiveFedora::Fedora Did you mean?
ActiveFedora::Fedora
```
This also removes an autoload to a constant that didn't exist (`Filter`)

Eager load ActiveFedora

---

lib/active_fedora/associations/basic_contains_association.rb
spec/integration/basic_contains_association_spec.rb

When doing a refresh of a basic container relationship, refresh the
membership triples on the parent object. This prevents an attempt to
load resources that have been deleted.  We're careful to only update the
membership triples, because we don't want to overwrite any in-memory
changes on the parent object.
Fixes https://github.com/projecthydra/hydra-head/issues/401
Fixes https://github.com/projecthydra/sufia/issues/3065

Refresh container resource triples

---

lib/active_fedora/attached_files.rb
lib/active_fedora/version.rb
spec/unit/attached_files_spec.rb

Also bumped the version because this is a critical fix.

Don't populate attached_files when using idiomatic basic containment

---

lib/active_fedora/inheritance.rb
spec/unit/inheritance_spec.rb

Fixes and adds tests for the following issue:
Given:
```
class A < ActiveFedora::File
end
class B < A
end
```
Expected:
```
> A.base_class
=> ActiveFedora::File
> B.base_class
=> ActiveFedora::File
```
Actual:
```
> A.base_class
=> ActiveFedora::File
> B.base_class
ActiveFedora::ActiveFedoraError: B doesn't belong in a hierarchy descending from ActiveFedora
from /Users/mbk836/Workspace/hydra/active_fedora/lib/active_fedora/inheritance.rb:18:in `base_class'
```

Fix ActiveFedora::Inheritance.base_class for deep File descendants

---

lib/active_fedora/attributes/property_builder.rb
lib/active_fedora/relation/finder_methods.rb
spec/unit/attributes_spec.rb

If these changes aren't related enough, I can split them into separate PRs.  But the gist is to print the Fedora object IDs when they are related to an AF error.  I also re-worded the error in `#raise_record_not_found_exception!` and inlined it into the only place where it's used.
I also had to add pry to the Gemfile to avoid this error during `bundle exec rake`:
```
rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --backtrace
Coverage report generated for RSpec to /Users/alex/clones/active_fedora/coverage. 246 / 477 LOC (51.57%) covered.
/Users/alex/clones/active_fedora/spec/spec_helper.rb:16:in `require': cannot load such file -- pry (LoadError)
from /Users/alex/clones/active_fedora/spec/spec_helper.rb:16:in `<top (required)>'
from …
```

print IDs in more error messages

---

lib/active_fedora/rake_support.rb

The following .internal_test_app/config/fcrepo_wrapper_test.yml was in
the Hyrax internal test application:
```yaml
port: 8986
enable_jms: false
fcrepo_home_dir: tmp/fcrepo4-test-data
```
I was able to run `fcrepo_wrapper -v -p 8986 --no-jms` locally and
Fedora would boot. If I ran `rake ci` Fedora failed to boot (with the
below error message)
Error log for Fedora boot failure via `rake ci` on the Hyrax project:
```console
[main] INFO org.eclipse.jetty.util.log - Logging initialized @1223ms
[main] INFO org.simplericity.jettyconsole.DefaultJettyManager - Added web application on path / from war /private/var/folders/gb/2k95hwkn1xd3zhs_gnmvpzt5xc_94p/T/fcrepo-webapp-4.7.1-jetty-console/fcrepo-webapp-4.7.1-jetty-console.jar
[main] INFO org.simplericity.jettyconsole.DefaultJettyManager - …
```

Fixing fcrepo_wrapper behavior in `with_server` task

---

lib/active_fedora/aggregation/list_source.rb

Without this, ActiveTriples can potentially get stuck in a never-ending
loop.

Empty out nodes directly.

---

README.md

The tests require Fedora to be running on port 8986, and we can't use a .fcrepo_wrapper config file because it conflicts with the generator integration test.

Update fcrepo_wrapper command in README to use the correct port

---

lib/active_fedora/indexing.rb
lib/active_fedora/indexing/descendant_fetcher.rb
spec/integration/indexing_spec.rb

by prioritizing URIs belonging to objects with certain hasModel literals.
By default the models used for Hydra::AccessControls permissions objects.
Because this method is used by reindex_everything, which in Hydra needs
to index permissions objects first.
The logic of keeping track of partitioned priority URLs got complex enough
that it made sense to pull it all out into it's own class, instead of trying
to add more class methods to the Indexing module.
Even though the use case for this is Hydra, I think it makes sense to put it in ActiveFedora, with Fedora::AccessControl defaults. 
* Many Hydra users are currently indexing with `ActiveFedora::Base.reindex_everything`. It is optimal if they can continue doing so but just have it work right (whether or not they even realized it wasn't …

Indexing#descendant_uris capable of prioritizing at front of list

---

active-fedora.gemspec
lib/active_fedora/indexing.rb
lib/active_fedora/solr_service.rb

* batched commits, on by default, but you can effectively turning it off by setting it to `1` (default `50`). 
Batched commits seem to very significantly speed up reindex_everything. 
everything else off by default but you can turn it on, other features to make a more pleasant and flexible reindex_everything experience:
* progress bar
* turn off softCommit, which was hard-coded on before
* Do a final hard commit, to ensure your `reindex_everything` is written to Solr disk.

#reindex_everything improvements

---

lib/active_fedora/indexing/map.rb
spec/unit/indexing/map_spec.rb

This enables you to construct a custom indexing map:
```ruby
class MyIndexer < ActiveFedora::RDF::IndexingService
protected
def index_config
super.merge(my_indexing_behavior)
end
def my_indexing_behavior
{ my_field: ActiveFedora::Indexing::Map::IndexObject.new ... }
end
end
```

Add Indexing::Map#merge

---

lib/active_fedora/indexing/map.rb
spec/unit/indexing/map/index_object_spec.rb

Previously we were resricted to setting behaviors in a block.
This new way is useful if we want to construct the index map manually,
not using the index hints on the model parameters

Indexing::Map::IndexObject takes behaviors as a parameter

---

lib/active_fedora/file.rb
spec/unit/file_spec.rb

uri is actually a method on file but since this file is still running initialize and obviously doesn't have a uri it throws a NoMethodError for subject_uri inside that method instead of raising the exception on line 43.  This PR uses the indentifier param to make the correct error message and narrows the unit test to expect a RuntimeError instead of any error.

Raise expected RuntimeError by using correct variable

---

lib/active_fedora/with_metadata/metadata_node.rb
spec/unit/with_metadata/metadata_node_spec.rb

I discovered this when working on external files.  Ldp::Resource is checking for subject.nil? which is not true for RDF::URI.new(nil).
https://github.com/projecthydra/ldp/blob/master/lib/ldp/resource.rb#L42
This should avoid some head requests and speed up the spec tests a little.

Pass nil instead of a nil RDF::URI as subject to Ldp::Resource to avoid head request

---

lib/active_fedora/with_metadata/metadata_node.rb
spec/unit/with_metadata/metadata_node_spec.rb

This PR builds on #1233 and fixes the resetting of metadata_uri so if you call save on the metadata node it will reinitialize with the described_by uri from it's parent file.

Metadata node save

---

lib/active_fedora/file_configurator.rb

I bumped into this while working on https://github.com/projecthydra-labs/hyku/pull/1052

YAML.safe_load - allow YAML aliases - loading solr.yml and fedora.yml

---

lib/active_fedora/fixity_service.rb
spec/unit/fixity_service_spec.rb

The fedora fixity service also reports the expected message
digest and file size. It makes sense to allow these to be accessed -- might be wanted for reporting/logging, especially on failure. 
Actually cache the http response. Comment erroneously implied
it was cached before, but it wasn't. #check still forces a new
check, as it did before this commit, but verified? is a more
clear method name for return value, and will not bust response
cache.
Cleaned up some erroneous comments.

more powerful ActiveFedora::FixityService

---

lib/active_fedora/version.rb

The version was last bumped in https://github.com/projecthydra/active_fedora/commit/c454338613d750c3a9b360736fb8ab3465e94aa1, but this is not in the master branch.  It’s on branch 11.1-stable, which is 37 behind master, 1 ahead — https://github.com/projecthydra/active_fedora/branches
That is, it looks like v11.1.6 is released but it did not bump https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/version.rb
https://github.com/projecthydra/active_fedora/releases has 11.1.6 already
Trying to follow https://github.com/projecthydra/active_fedora/wiki/Release-management-process but confused about the state of the last release vs. the master branch and whether or not to release 11.1.7 against the master branch?
Also wondering whether a new release is a minor or patch …

Release 11.2.0

---

lib/generators/active_fedora/config/solr/templates/solr.yml

- honor SOLR_URL in all 3 environments
- Use 127.0.0.1 for both dev and test
- fix copy/paste error repetition of SOLR_TEST_PORT in dev environment
See also: 
- https://github.com/projecthydra-labs/hyrax/issues/1016
- https://github.com/projecthydra/hydra-head/pull/411

Make solr.yml consistent w/ blacklight.yml (and itself)

---

lib/active_fedora/file/attributes.rb
spec/unit/file_spec.rb

ActiveFedora::Base objects have `.modified_date` alongside a `.create_date`, but ActiveFedora::File objects only have a `.create_date`.  This PR adds a `.modified_date` to match and make it easier to get the last modified date for a NonRdfSource.

File metadata should have a modified_date

---

.travis.yml
Gemfile

2.0.2 is the latest and will be installed by default.

No need to set RSolr 2.0 explicitly

---

lib/active_fedora/persistence.rb

We almost always follow up a HEAD request with a GET request, so don't
bother with the HEAD request. The GET gives us all the information we
need.

Call get instead of HEAD + GET

---

lib/active_fedora/common.rb
spec/unit/core_spec.rb

The specs guarantee that the ETag will be the one returned by the base object's `#ldp_source`.
This allows a fix for a [to do item in `Hyrax::WorkBehavior`](https://github.com/samvera/hyrax/blob/bf1ba8057da3212a32e3c30d070ba6d85cb8128a/app/models/concerns/hyrax/work_behavior.rb). The implementation is slightly different from the one there, to avoid
reaching outside of `ActiveFedora::Common`. The functional difference is that deleted objects will raise `Ldp::Gone` instead of `RuntimeError`; this error is more informative and `Ldp::Gone` is a subclass of
`RuntimeError`.

Allow access to ETag with `AF::Common#etag`

---

lib/active_fedora/persistence.rb

We almost always follow up a HEAD request with a GET request, so don't
bother with the HEAD request. The GET gives us all the information we
need.

[backport] Call get instead of HEAD + GET

---

lib/active_fedora/common.rb
spec/unit/core_spec.rb

The specs guarantee that the ETag will be the one returned by the base
object's `#ldp_source`.
This allows a fix for a [to do item in
`Hyrax::WorkBehavior`](https://github.com/samvera/hyrax/blob/bf1ba8057da3212a32e3c30d070ba6d85cb8128a/app/models/concerns/hyrax/work_behavior.rb). The
implementation is slightly different from the one there, to avoid
reaching outside of `ActiveFedora::Common`. The functional difference is
that deleted objects will raise `Ldp::Gone` instead of `RuntimeError`;
this error is more informative and `Ldp::Gone` is a subclass of
`RuntimeError`.

[backport] Allow access to ETag with `AF::Common#etag`

---

lib/active_fedora/relation/finder_methods.rb

This error also indicates an out-of-sync index

Rescue ObjectNotFoundError in find_each

---

lib/active_fedora/fedora.rb
spec/unit/fedora_spec.rb

When attempting to run reindex_everything, my Fedora instance sits in silence for 10+ minutes before returning the first bytes of a response to a get request of the base path.  Faraday throws a timeout after a few seconds so I need to be able to configure it to allow for these abnormally long periods of waiting.

Request options allow for setting timeout of Fedora client

---

lib/active_fedora/errors.rb
lib/active_fedora/ldp_resource.rb
lib/active_fedora/relation/finder_methods.rb
spec/integration/base_spec.rb
spec/integration/scoping_spec.rb

Fixes #1276 
Resolve failing test with a distinct error class, allowing `exists?` to catch the new error as well as
`ObjectNotFoundError`, returning `false`.
- Refactored tests to reuse ad hoc classes
- added negative tests for `#find`
- Consolidated single-line single-use private methods

Prevent `exists?` from throwing exceptions

---

lib/active_fedora/indexing/descendant_fetcher.rb
spec/integration/indexing/descendant_fetcher_spec.rb

This PR preserves previous functionality for grouping uris by priority/other but also adds the capability to get the uris grouped by model if you call `descendant_and_self_uris_partitioned_by_model` directly.

Allow the descendant fetcher to be more flexible by grouping uris by model

---

lib/generators/active_fedora/config/solr/templates/solr/config/schema.xml

As per same fix in blacklight: https://github.com/projectblacklight/blacklight/commit/b88b93ab7cfffb03117f47b6cd92a9bde5426d6d
and hyrax:
https://github.com/samvera/hyrax/pull/1711

Remove deprecated defaultOperator and defaultSearchField solr configs

---

lib/active_fedora.rb
lib/active_fedora/file_io.rb
spec/unit/file_io_spec.rb

This adds an IO like way to use ActiveFedora::Files. This will make it easier to handle files as streams rather than loading the entire contents in memory, which should always be avoided for obvious reasons. file.stream.each offers a similar mechanism (and this PR is based on that) but since it's not IO-like, it's not as simple to use with other tools.
For example in here https://github.com/samvera/hyrax/blob/master/app/services/hyrax/working_directory.rb#L36 the StringIO could immediately be replaced with this IO like object to avoid loading the contents in memory.

Add an IO like object for Fedora files

---

lib/active_fedora/solr_service.rb
spec/unit/solr_service_spec.rb

Backports #1283 to the 11.x series.

Allow SolrService to submit queries via HTTP POST

---

lib/active_fedora/attributes/property_builder.rb
spec/unit/attributes_spec.rb

Some `RDF::Term` objects implement `#each`, including `ActiveTriples::RDFSources`. The old checks for singular fail on simple cases like `work.single = RDF::Node.new; work.single = work.single`. The new check has a special case for terms.
Ideally, we could check something like `#to_ary`, but behavior is not consistent across the relevant dependency libraries. E.g. `ActiveTriples::Relation#to_ary` is unimplemented, while `RDF::Queryable#to_ary` is (the opposite would be better for our use).

Treat `RDF::Term` implementers as singular values

---

lib/active_fedora/attributes/property_builder.rb
spec/unit/attributes_spec.rb

This is a minimal replacement for the more comprehensive fix in the reverted
3c21a7d.
Some `RDF::Term` objects implement `#each`, including
`ActiveTriples::RDFSources`. The old checks for singular fail on simple cases
like `work.single = RDF::Node.new; work.single = work.single`. The new check has
a special case allowing terms as single valued properties. Checking for
multivalued fields remains broken to support legacy code that accidentally takes
advantage of the bug.
Presently, both `work.my_property = ''` and `work.my_property = RDF::Node.new`
are allowable sets for multivalued fields.

Treat resources as allowable single valued properties

---

lib/active_fedora/relation/finder_methods.rb
spec/unit/finder_methods_spec.rb

It was in use by Hyrax (see
https://github.com/samvera/hyrax/issues/2482)  This was removed in https://github.com/samvera/active_fedora/pull/1277

Restore equivalent_class? method

---

lib/active_fedora/fedora.rb
lib/active_fedora/indexing/descendant_fetcher.rb

This PR proposes to request ntriples when gathering the descendants for reindexing.  
Due to the number of child nodes on the base path requesting it can take a really long time to return the whole rdf document.  If the default turtle serialization is used the entire document has to be prepared prior to returning anything to the client (AF) leading to timeouts.  Switching to ntriples allows the document to stream back avoiding the timeout issues.
Related discussion:
https://jira.duraspace.org/browse/FCREPO-2544
https://groups.google.com/d/topic/samvera-tech/FPSFJubcPn8/discussion

Request ntriples when fetching descendants to avoid timeout issues

---

lib/active_fedora/simple_datastream.rb
spec/unit/simple_datastream_spec.rb

This allows downstream users to use fields that conflict with public AF methods. Case in point: I need to support a field named "prefix" which entered the public API around AF 7.0.0.

Prefer om_term_values to send when solrizing within SimpleDatastream

---

lib/generators/active_fedora/config/solr/templates/solr/config/schema.xml

Port of @atz's commit in hydra-head: https://github.com/samvera/hydra-head/pull/418/commits/cc263441af6e3561b66e508c1428959005e3b924
This change was ported due to hydra-head's removal of its solr configuration in favor of this config generated by active_fedora. (https://github.com/samvera/hydra-head/pull/432)
See https://github.com/samvera/hydra-head/issues/417 for more details.

Add Solr dateRange field type and dynamic fields to schema.xml

---

.travis.yml
active-fedora.gemspec
lib/active_fedora/aggregation/list_source.rb
lib/active_fedora/attribute_methods.rb
lib/active_fedora/attribute_methods/read.rb
lib/active_fedora/attribute_methods/write.rb
lib/active_fedora/attributes.rb
lib/active_fedora/file.rb
lib/active_fedora/inheritable_accessors.rb
lib/active_fedora/with_metadata/metadata_node.rb
spec/integration/file_spec.rb
spec/support/an_active_model.rb

This PR takes pieces of #1310 and https://github.com/samvera/rubydora/pull/110 and attempts to build on them to do the rest necessary to fix support for Rails 5.2.  I have to admit that I'm not certain these changes are correct but the test suite passes.  These changes are needed to fix the builds of downstream gems (hydra-pcdm, hydra-works, and potentially others) which are currently broken if they don't pin to older versions of rails.
Fixes https://github.com/samvera/hydra-pcdm/issues/248

Fix support for Rails 5.2

---

active-fedora.gemspec
lib/active_fedora/validations.rb
spec/unit/validations_spec.rb

As reported various times (https://github.com/samvera/active_fedora/issues/914, https://github.com/samvera/active_fedora/pull/797, https://github.com/avalonmediasystem/avalon/pull/2984), it looks like validation callbacks aren't running.  
This PR adds a test case for before and after validation callbacks and then copies the code used in ActiveModel: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/callbacks.rb#L114-L119

Run and test validation callbacks

---

lib/active_fedora/associations/collection_proxy.rb
lib/active_fedora/relation.rb
lib/active_fedora/relation/delegation.rb
spec/integration/relation_spec.rb

`Relation#each` had previously delegated to `Relation#to_a`, which sends
N requests to Fedora (plus one to Solr) and loads all the objects into memory
before beginning work.
This introduces an `Enumerator` based implementation, using `#find_each`. When
`#to_a` has already been called, we take advantage of the existing caching;
otherwise we yield items individually.
We also delegate certain other methods to `#each` instead of `#to_a`,
extending the same benefits to `#collect`, and getting massively
better performance from `#blank?`, `#present?`, `#include?` and `#any?`. There
are probably other optimizations to be explored based on this.
`#map` is kept as is, since delegating it to `#each` breaks ordering code. Since
it would be rasonable to assume that `#map` would have effient access …

Implement enumeration for `Relation#each`

---

active-fedora.gemspec

ActiveFedora 11.5 *does not* support Rails 5.2.

Pin to Rails 5.1

---

active-fedora.gemspec

Rails can break on minor changes. Supporting `< 6` is optimistic and leads to
version problems.
`ldp` has recently released 1.0.0; supporting this will help adopters ensure
stability.

Limit support to Rails 5.2; add support for `ldp` 1.0

---

.travis.yml
Gemfile

rather than the version of activemodel.
This prevents the tests from installing rails 0.9.5, and not finding the generator code we depend on.

Pin the version of rails that is used

---

lib/generators/active_fedora/config/solr/templates/solr/config/schema.xml

I'm re-submitting this PR from @jcoyne 
This filter is deprecated and according to the solr docs it is
inoperative if "luceneMatchVersion (in solrconfig.xml) is higher than
3.1."  The luceneMatchVersion in active_fedora is currently 5.0.0
See https://lucene.apache.org/solr/guide/7_0/filter-descriptions.html#FilterDescriptions-StandardFilter

Remove deprecated Solr StandardFilter

---

active-fedora.gemspec
lib/active_fedora.rb
lib/active_fedora/indexing.rb
lib/active_fedora/indexing/descriptor.rb
lib/active_fedora/indexing/field_mapper.rb
lib/active_fedora/indexing/suffix.rb

The community decided to proceed with deprecating the Solrizer Gem on April 26th, 2018 (please see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/samvera-tech/gjN6DjjnaEA/oGWoVtHFAAAJ)

Removes the dependency for solrizer

---

lib/active_fedora/version.rb

This will ensure that the changes introduced in https://github.com/samvera/active_fedora/pull/1383 become available with a new patch release.

Releases version 12.2.0

---

lib/generators/active_fedora/config/solr/solr_generator.rb

Blacklight generates Solr configuration into `solr/conf`. Since ActiveFedora now
generates its configurations into the same directory, any differing files will
be treated as conflicts by `Rails::Generators::Base`. Adding `force: true` to
the step that copies these files ensures that the AF versions of these files are
installed without requiring confusing user feedback at generation time.

Force overwrite of `solr/conf` files if they have changes

---

.circleci/config.yml
active-fedora.gemspec

The CCWG says we have to support Ruby 2.4, so we're readding, but without the
tests for Rails 6.0 (which won't bundle).

Readd support for Ruby 2.4.7

---

lib/active_fedora/aggregation/list_source.rb
lib/active_fedora/attributes.rb

This method can be replaced by `ActiveModel::Dirty#changes_applied`, which is
more resiliant to changing `ActiveModel` and `Rails` behavior.
However, since we call it in a callback, and downstream users may be relying on
that fact to trigger calls to their overrides, we continue calling it in the
case that it is both: not the base definition, and not the version overridden in
`ListSource`.
Callers to those two versions will see deprecation warnings, and users of the
callback will also see deprecation warnings. Their local behavior may be in
conflict with Rails 6.0.

Deprecate `#clear_changed_attributes`

---

active-fedora.gemspec
lib/active_fedora/version.rb

This currently blocks https://github.com/samvera/hydra-editor/pull/180 due to https://github.com/ma2gedev/faraday-encoding/commit/dc749230d4dd71dedc4b2703a7bb62ac1ea8f7c9 being introduced in `faraday-encoding` release 0.0.5.

Upgrades the dependency for faraday-encoding in order to ensure that FrozenError is not raised for HTTP request body content; Releases 13.1.1

---

lib/active_fedora/file.rb
spec/unit/file_spec.rb

This bug was causing https://github.com/samvera/hyrax/issues/4018 but could also be the source of many more issues.
In the issue above this manifested with the extracted text file being read by indexing prior to the actual persisting to fedora at which point it was already consumed and an empty file was sent to fedora.
BE KIND, REWIND!

Always rewind IO content even when the file is new.

---

active-fedora.gemspec

Removing the test_files from the gemspec ensures that consumers of the Gem are not required to download any fixture files with the Gem (please see https://github.com/samvera/hyrax/pull/4245 for the origin discussion).

Removing spec files from gem distribution

---

active-fedora.gemspec
lib/active_fedora/with_metadata/default_schema.rb

This is necessary given that this term was removed: https://github.com/ruby-rdf/rdf-vocab/blob/develop/lib/rdf/vocab/ebucore.rb#L7117. Please see https://github.com/samvera/hydra-derivatives/pull/221 for context.

Updating the EBUCore term for `RDF::Vocab::EBUCore.filename`

---

active-fedora.gemspec
lib/active_fedora/with_metadata/default_schema.rb

Introduces the solution proposed in https://github.com/samvera/active_fedora/pull/1421#issuecomment-642817917

Pinning rdf-vocab to versions previous to 3.1.5

---

active-fedora.gemspec

avoids changes to the EBUCore vocabulary that would force data migrations for
downstream users.

pin `rdf-vocab` to versions prior to 3.1.5

---

config/fedora.yml
lib/generators/active_fedora/config/fedora/templates/fedora.yml

in general, we'd like to support 12-factor style configuration:
https://12factor.net/config
the older, rails-influenced approach makes it challenging to handle different
configurations across many environments for one app. by using generic ENV
variables, but supporting more specific ones, and falling back on  hard coded
values we can have it both ways.
this implementation should continue to support older configurations in exactly
the same way, but also allow users to adopt one variable name across
environments.

improve configurability of Fedora for downstream apps

---

lib/active_fedora/orders/ordered_list.rb

The initialization line:
```ruby
@node_cache ||= NodeCache.new
```
suggests that the node cache might have been supplied through other means, but there's currently not possible; the proposed change allows for it.
This is a change we made within a project to fix a production bug in the component that built an arbitrarily large and deep set of nested OrderedList objects, before saving it -- without the ability to pass along an existing, paritlally-populated, node cache, we were getting collisions on ids once the whole set was persisted.

Allow initializing OrderedList with an existing NodeCache

---

lib/active_fedora/aggregation/list_source.rb

ActiveModel::Dirty will attempt to load the entire ordered list when calling nodes_will_change! which leads to a stack level too deep exception in some cases (samvera/hyrax#4581).
This approach was also taken in ActiveFedora::File: 7c8bbbe#diff-28356c4daa0d55cbaf97e4269869f510R100-R103

Short circuit ActiveModel::Dirty for nodes_will_change!

---

lib/active_fedora/ldp_resource.rb

LDP tried to add an optimization reusing the underlying data structure from the
response's already existing parsed graph. our implementation in prior releases
blocked that. but since we're overriding anyway, no harm in adding it back.

re-add optimization from ldp 1.0.2

---

lib/active_fedora/core.rb
spec/integration/base_spec.rb

Fixes #1388 
This adds a rescue block to the reload method in core; it handles the case where two copies of an object are live, one is destroyed, but reload is called the other which will not have the destroyed flag set, resulting in uncaught Ldp::Gone, rather than the expected ActiveFedora::ObjectNotFoundError.
This scenario can occur in Hyrax when the wings module is in use; a monkey patch by @no-reply to temporarily handle this in Hyrax is in progress.

core reload rescue edge case

---

lib/active_fedora/indexing/descendant_fetcher.rb

only loop through possibly large collections once.
in the case of the repository root, the number of object in these collections is
potentially hundreds of thousands or millions of objects. restricting ourselves
to a single iteration is helpful, and `RDF::Enumerable#each_object` presents a
single upstream method to house memory optimizations.
the older implementation seemed pre-occupied with preventing repeated `#to_s`
calls. this isn't necessary since these are cheap variable dereferences in
almost all relevant cases.

compact some potentially large scale iterations in reindex_all

---

active-fedora.gemspec
lib/active_fedora/file.rb

Replaces the other instance of deprecated URI encoding following the same pattern as in #1456

Replace deprecated URI.encode with updated call

---

lib/active_fedora/with_metadata/default_schema.rb
lib/active_fedora/with_metadata/default_strategy.rb
lib/active_fedora/with_metadata/metadata_node.rb
spec/integration/with_metadata_spec.rb

Upstream port of monkey-patch in Hyrax required for wings (https://github.com/samvera/hyrax/pull/5320)
This PR introduces an attribute on properties in the metadata schemas called `:server_managed`.  When this attribute is set to true on a property it allows a value to be set via the generated setter but the change isn't tracked by `ActiveModel::Dirty` and subsequently isn't sent to the server as part of the changed values when saving.

Don't track changes or attempt to persist server-managed properties on file metadata nodes

---

lib/active_fedora/version.rb

This release would include the changes to handle URI encoding deprecation warnings in ruby 2.7 and the handling server managed properties in file metadata nodes.

Prepare release 13.2.5

---

lib/active_fedora.rb

Resolves #1466 
RDF 3.2.5 changed the superclass of DateTime which broke the monkey patch in ActiveFedora.  This PR conditionally applies the monkey patch if the class exists.  
It appears that the monkey patch might not be necessary with RDF 3.2.5 due to the changes to the class in RDF (see https://github.com/ruby-rdf/rdf/releases/tag/3.2.5) so I didn't attempt to create a new version of the monkey patch.  But I removed the monkey patch and all the tests passed locally with RDF 3.2.4 so maybe the changes aren't actually being tested properly or aren't necessary anymore due to improvements in Fedora 4 or ActiveFedora since the monkey patch was applied in 2014? :man_shrugging: 
Within the CI environment the monkey patch should still be getting applied for the ruby 2.5 build because RDF …

Conditionally apply monkey patch to handle versions of RDF 3.2.5+

---

lib/active_fedora/version.rb

This release would only include the fix for working with rdf  version 3.2.5+ (https://github.com/samvera/active_fedora/pull/1468)

Prepare for release 13.2.6

---

lib/active_fedora.rb
spec/integration/date_time_properties_spec.rb

Fixes #1466 an d #1471 
This allows the monkey-patch to work with either rdf <= 3.2.4 or rdf >= 3.2.5
The monkey-patch is necessary to maintain the current behavior of nanosecond precision in dates
Failing tests in hyrax revealed this so tests were added here to test this functionality
Note that rdf 3.2.0+ require ruby >= 2.6 so the ruby 2.5 circleci builds should be testing with rdf < 3.2.5 while the ruby 2.6 and 2.7 builds should be testing with rdf = 3.2.5.

Remove the explicit superclass from monkey-patch

---

lib/active_fedora/version.rb

ActiveFedora 13.2.6 was yanked due to the change to the rdf monkey-patch losing sub second precision past milliseconds. This patch release would only include #1472, a better fix for this issue.

Prep for release 13.2.7

---

lib/active_fedora/version.rb

Backports:
- #1456 - Ruby 2.7 deprecation warnings
- #1463 - Ruby 2.7 deprecation warnings
- #1472 - Compatibility with newer rdf 3.2.5

Prepare for release

---

lib/active_fedora/querying.rb

not all models have an indexer (e.g. `ActiveFedora::File` inheritors do
not). trying to query them with `MyModel.all` shouldn't raise a `NameError`.

don't try to delegate ""system_create_dtsi" to `#indexer`

---

lib/active_fedora/version.rb

Includes:
- #1483 (Rails 6.1 Support)
- #1480 (README Badges)
- #1462 (Handle RSolr Deprecation of read_timeout)
- #1460 (Don't delegate system_dtsi to #indexer)
- #1453 (Update README/CONTRIBUTING)

Prepare for release 13.3.0

---

active-fedora.gemspec
lib/active_fedora/version.rb

Includes:
- #1489 
Also resolves #1481 
Making this a major release (14.0.0) because ruby 2.4 and 2.5 are explicitly being dropped in order to bring in a newer version of `json-ld`.

Release 14.0.0

---

lib/active_fedora/autosave_association.rb
spec/unit/ordered_spec.rb

When attempting to upgrade Avalon to rails 7.0, I ran into an error about modification of frozen arrays, but the real issue was that Rails 6.1 included a major change in `ActiveModel::Error` turning it into an array of objects instead of a simple hash.  The API changed and I had to find an approach that worked for all versions of Rails that ActiveFedora supports.  I think the approach I took is a stop gap and that we'll want to rework this using the new API more and possibly rethinking this section entirely.  Currently the errors are surfaced on the parent object by composing the child association name with the attribute of the child which has the error.  This is problematic because the new `ActiveModel::Error` implementation checks if error keys are actual attributes on the model object. …

Avoid modifying frozen array

---

lib/active_fedora/attribute_methods.rb
spec/unit/attributes_spec.rb

Found by @randalldfloyd in the Hyrax test suite when attempting to upgrade to rails 7.2.  This is an untested incompatibility with rails 7.1+ that once fixed will need to go into a patch release.

Use to_formatted_s(:db) instead of deprecated and removed to_s(:db)
