samvera/active_fedora

lib/active_fedora/nested_attributes.rb
spec/integration/rdf_nested_attributes_spec.rb

After setting nested rdf attributes, mark the attributes as changed. 

---

lib/active_fedora/version.rb

Bumped version to 8.0.0

---

lib/active_fedora/file.rb
lib/active_fedora/fixity_service.rb
lib/active_fedora/rdf/fcrepo4.rb

Use Fcrepo4 class repository definitions

---

lib/active_fedora/attached_files.rb
lib/active_fedora/file.rb
spec/integration/attached_files_spec.rb
spec/integration/file_spec.rb
spec/unit/attached_files_spec.rb
spec/unit/file_spec.rb

use #add_file and :path as the parameter instead

Deprecate File#add_file_datastream and the dsid parameter

---

lib/active_fedora/file.rb
spec/integration/file_spec.rb

instead of yielding directly.
Attempting to follow this pattern:
https://github.com/rails/rails/blob/08754f12e65a9ec79633a605e986d0f1ffa4b251/actionpack/lib/action_controller/metal/data_streaming.rb#L81-L96
which should let us set `self.response_body = file.stream` in a
controller

File#stream should return a FileBody object

---

lib/active_fedora/fedora.rb
lib/active_fedora/file.rb
lib/tasks/active_fedora_dev.rake
spec/unit/active_fedora_spec.rb

Addresses #716 and provides support for making connections to Fedora using basic authorization.

Support basic authorization to Fedora

---

lib/active_fedora/relation/finder_methods.rb
lib/active_fedora/solr_query_builder.rb
spec/integration/query_result_builder_spec.rb

Merge this depending on what you're thoughts are on rsolr/rsolr#101

Use modified RSolr.solr_escape method

---

lib/active_fedora/core.rb

This refactor removes a net 10 lines of code, making the initialization process easier to understand. I've also changed a method and some variable names to better reflect their true purposes.

Refactor the AF::Base initializer

---

lib/active_fedora/relation/finder_methods.rb
spec/integration/belongs_to_association_spec.rb

Most specific model class should be loaded, by using an inheritance structure if present.

Content model inheritance

---

.travis.yml
lib/active_fedora.rb
lib/active_fedora/associations.rb
lib/active_fedora/associations/delete_proxy.rb
lib/active_fedora/associations/indirectly_contains_association.rb
lib/active_fedora/associations/record_proxy_finder.rb
lib/active_fedora/containers/container.rb
lib/active_fedora/fedora.rb
lib/active_fedora/fedora_attributes.rb
lib/active_fedora/inbound_relation_connection.rb
lib/active_fedora/rdf/fcrepo4.rb
spec/integration/indirect_container_spec.rb

Delete Indirect Proxies

---

lib/active_fedora/associations/record_proxy_finder.rb
spec/integration/indirect_container_spec.rb

Indirect container delete bug

---

History.txt
lib/active_fedora/version.rb

Patches casting behavior (#777).

Version 8.1.0

---

lib/active_fedora.rb
lib/active_fedora/attributes.rb
lib/active_fedora/attributes/active_triple_attribute.rb
lib/active_fedora/attributes/om_attribute.rb
lib/active_fedora/attributes/rdf_datastream_attribute.rb
lib/active_fedora/attributes/stream_attribute.rb
lib/active_fedora/delegated_attribute.rb
spec/unit/attributes_spec.rb

Day One of ActiveFedora Conclave. This refactors DelegatedAttribute into three different subclasses for better code organization.

Refactoring DelegatedAttribute

---

spec/integration/belongs_to_association_spec.rb
spec/integration/has_many_associations_spec.rb

Autosave should not be included when it's not needed and should be tested to ensure it saves changes to existing objects

Make autosave tests more specific

---

lib/active_fedora/solr_query_builder.rb
spec/unit/solr_query_builder_spec.rb
spec/unit/solr_service_spec.rb

This allows the query to be smaller and more understandable

Use the solr terms query when fetching by id

---

lib/active_fedora/file.rb
lib/active_fedora/identifiable.rb
spec/integration/directly_contains_one_association_spec.rb
spec/unit/pathing_spec.rb

The uri() method should return an RDF::URI

---

lib/active_fedora/relation.rb
spec/integration/relation_spec.rb

Relation should respond to enumerable methods

---

lib/active_fedora/change_set.rb
spec/unit/change_set_spec.rb

This became a problem with inbound relations being in the same graph.

ChangeSet shouldn't record other subjects.

---

lib/active_fedora/loadable_from_json.rb
spec/integration/solr_instance_loader_spec.rb

Fixes #856
I reorganised the code a bit compared to what I posted in the issue discussion. spec/integration/solr_instance_loader_spec.rb already had similar tests so I moved my tests there instead.

Improve handling of imperfect profile_json when loading instances from Solr.

---

lib/active_fedora/associations/collection_association.rb
spec/integration/collection_association_spec.rb

Don't delete unrelated objects in Collection Association

---

lib/active_fedora/associations/association.rb
lib/active_fedora/associations/basic_contains_association.rb
lib/active_fedora/associations/belongs_to_association.rb
lib/active_fedora/associations/collection_association.rb
lib/active_fedora/associations/directly_contains_one_association.rb
spec/integration/associations_spec.rb

Don't run type validators on destroy.

---

lib/active_fedora/indexing.rb

Add high-level comment for Indexing module.

---

spec/integration/nested_attribute_spec.rb

Originally from https://github.com/projecthydra/active_fedora/pull/879
Thanks to @ojlyytine

Refactor nested_attribute_spec

---

lib/active_fedora/indexing_service.rb
lib/active_fedora/rdf/indexing_service.rb

As a bonus, also removes a trailing whitespace.
Related to @2f405cb94f95020a7e85dc974d5321ef5c17fd64
[skip ci]
ATTN: @hackmastera

Updating documentation of Indexing Service

---

lib/active_fedora/loadable_from_json.rb
spec/integration/solr_instance_loader_spec.rb

Fixes projecthydra/active_fedora#870.

Append val to solr array instead of replacing when appropriate.

---

lib/active_fedora/associations/indirectly_contains_association.rb
spec/integration/indirect_container_spec.rb

Don't load all the members of an IndirectContainer on concat

---

lib/active_fedora/associations/builder/indirectly_contains.rb
lib/active_fedora/associations/indirectly_contains_association.rb
spec/integration/indirect_container_spec.rb

This will enable us to resolve a performance concern.
see https://github.com/projecthydra-labs/hydra-pcdm/issues/193

Create an ids_reader for indirect containers

---

lib/active_fedora/rdf/fcrepo.rb

Adds :PID property to ActiveFedora::RDF::Fcrepo::Model vocab

---

lib/active_fedora/file.rb
spec/unit/file_spec.rb

Adds :update callback.
Callbacks were previously defined on AF::File, but not run.

Runs AF::File callbacks (fixes #972)

---

lib/tasks/active_fedora_dev.rake

Because rubocop dissallows byebug

Add a rake task for running spec without rubocop

---

lib/active_fedora/rake_support.rb

This will enable Hydra-head to provide a rake task that starts up a
development server.

Generalize the with_server method

---

.rubocop.yml
lib/active_fedora/associations/builder/association.rb
lib/active_fedora/associations/builder/belongs_to.rb
lib/active_fedora/associations/builder/collection_association.rb
lib/active_fedora/associations/builder/contains.rb
lib/active_fedora/associations/builder/directly_contains.rb
lib/active_fedora/associations/builder/directly_contains_one.rb
lib/active_fedora/associations/builder/has_and_belongs_to_many.rb
lib/active_fedora/associations/builder/has_many.rb
lib/active_fedora/associations/builder/indirectly_contains.rb
lib/active_fedora/associations/builder/property.rb
lib/active_fedora/associations/builder/singular_association.rb
lib/active_fedora/associations/builder/singular_property.rb
lib/active_fedora/attribute_methods.rb
lib/active_fedora/autosave_association.rb
spec/unit/base_spec.rb
spec/unit/builder/has_and_belongs_to_many_spec.rb

Slowly pulling our associations code up to date with the latest Rails developments.

Begin updating associations to latest Rails conventions

---

lib/active_fedora/associations/collection_association.rb
spec/integration/collection_association_spec.rb

Brings the code into line with the current version of ActiveRecord
Fixes #1030

Correctly find the size of a collection in memory

---

.rubocop.yml
lib/active_fedora/associations/association_scope.rb
lib/active_fedora/associations/belongs_to_association.rb
lib/active_fedora/associations/builder/association.rb
lib/active_fedora/associations/builder/belongs_to.rb
lib/active_fedora/associations/builder/collection_association.rb
lib/active_fedora/associations/builder/contains.rb
lib/active_fedora/associations/builder/directly_contains.rb
lib/active_fedora/associations/builder/directly_contains_one.rb
lib/active_fedora/associations/builder/has_and_belongs_to_many.rb
lib/active_fedora/associations/builder/has_many.rb
lib/active_fedora/associations/builder/indirectly_contains.rb
lib/active_fedora/associations/builder/property.rb
lib/active_fedora/associations/builder/singular_association.rb
lib/active_fedora/associations/builder/singular_property.rb
lib/active_fedora/associations/collection_association.rb
lib/active_fedora/associations/has_many_association.rb
lib/active_fedora/attached_files.rb
lib/active_fedora/core.rb
lib/active_fedora/errors.rb
lib/active_fedora/reflection.rb
spec/unit/collection_proxy_spec.rb
spec/unit/has_and_belongs_to_many_association_spec.rb
spec/unit/has_many_association_spec.rb
spec/unit/reflection_spec.rb

First stab at aligning with Rails conventions.

Update reflections and associations

---

active-fedora.gemspec

activesupport 4.2.3 does not work. See
https://travis-ci.org/projecthydra/active_fedora/builds/118981758
and
https://travis-ci.org/projecthydra/active_fedora/builds/118984484

Use a version of activesupport >= 4.2.4

---

lib/active_fedora/rake_support.rb

This supports running under a gem, where the generators are not run.

Restore defaults to with_server

---

lib/active_fedora/associations/collection_association.rb
spec/integration/indexing_spec.rb
spec/unit/has_many_association_spec.rb

From HasManyAssociation#ids_reader
See projecthydra/hydra-head#267

Filter out records marked_as_deleted

---

lib/active_fedora/indexing_service.rb
lib/generators/active_fedora/config/solr/templates/solr/config/solrconfig.xml
solr/config/solrconfig.xml
spec/unit/indexing_spec.rb
spec/unit/query_spec.rb

We are using has_model_ssim for this capability

Stop indexing on active_fedora_model_ssi

---

.rubocop.yml
active-fedora.gemspec
lib/active_fedora/autosave_association.rb
lib/active_fedora/nested_attributes.rb
spec/integration/datastream_rdf_nested_attributes_spec.rb
spec/integration/has_and_belongs_to_many_associations_spec.rb
spec/integration/scoped_query_spec.rb
spec/samples/hydra-mods_article_datastream.rb

Fixing rubocop so that other commits to this branch will get a green build.

Fixing rubocop for latest version

---

lib/active_fedora/rdf/rdf_datastream.rb

See https://github.com/rails/rails/pull/17227

Throw abort to terminate callbacks

---

lib/active_fedora/associations/has_subresource_association.rb
lib/active_fedora/attribute_assignment.rb
lib/active_fedora/containers/container.rb
lib/active_fedora/core.rb
lib/active_fedora/file.rb
spec/integration/eradicate_spec.rb
spec/integration/ntriples_datastream_spec.rb
spec/unit/base_spec.rb
spec/unit/has_and_belongs_to_many_association_spec.rb
spec/unit/has_many_association_spec.rb
spec/unit/orders/list_node_spec.rb
spec/unit/query_spec.rb

Deprecated in https://github.com/projecthydra/active_fedora/pull/1126
Fixes #1122

Remove ActiveFedora::Base#initialize with a String argument

---

active-fedora.gemspec

Includes my rubocop_rspec_bump PR's change also.

Solr wrapper bump

---

lib/active_fedora/associations/has_many_association.rb
spec/unit/has_many_association_spec.rb

Prevously we were using property, but we recently stopped using
property, so it isn't finding the correct relation.

Lookup inverse using predicate

---

lib/active_fedora/solr_query_builder.rb
spec/unit/query_spec.rb
spec/unit/solr_config_options_spec.rb

Querying for relationships should use solr raw query

---

active-fedora.gemspec
lib/active_fedora/associations/contained_finder.rb
lib/active_fedora/change_set.rb
lib/active_fedora/fedora_attributes.rb
lib/active_fedora/orders/ordered_list.rb
spec/unit/with_metadata/metadata_node_spec.rb

Upgrade to ActiveTriples 0.11

---

active-fedora.gemspec

Reverts baa07cc9b1882434cc983c074a905eadbda4f8ef
because https://github.com/lsegal/yard/issues/947 is resolved

There is no need to pin rake any longer

---

.travis.yml
active-fedora.gemspec
lib/active_fedora/associations/collection_association.rb
lib/active_fedora/associations/collection_proxy.rb
lib/active_fedora/attribute_methods.rb

Also had to update the build matrix and rubocop to get the build back on track.

Replace deprecated Fixnum with Integer

---

active-fedora.gemspec

Propose releasing 7.3.1 following this fix.

Fix dependency snafu

---

lib/active_fedora/associations/basic_contains_association.rb

Get a fresh copy from Fedora.
Fixes https://github.com/projecthydra/hydra-head/issues/403
Fixes https://github.com/projecthydra/sufia/issues/3065

When updating triples avoid the cache

---

active-fedora.gemspec

Bump rspec requirement to ~>3.5

---

active-fedora.gemspec

Bump LDP version to ~> 0.7.0

---

active-fedora.gemspec
lib/active_fedora/fedora.rb
spec/integration/file_spec.rb

Set the proper string encoding on responses

---

lib/active_fedora/version.rb

This ought to keep people from accidentally releasing breaking changes into the 11.x release series.

Bump version to 12.0.0.alpha

---

lib/active_fedora/solr_service.rb
spec/unit/solr_service_spec.rb

Allow SolrService to submit queries via HTTP POST

---

active-fedora.gemspec

ActiveTriples is going to 1.0; yay!

Add support for ActiveTriples 1.0.0

---

active-fedora.gemspec
lib/active_fedora/version.rb

Bump version and fixup gemspec.

Prepare release 12.0.0

---

README.md
spec/spec_helper.rb

Adding the Coveralls badge and restructuring spec helper for Coveralls reporting

---

History.txt
active-fedora.gemspec
lib/active_fedora.rb
lib/active_fedora/aggregation/list_source.rb
lib/generators/active_fedora/model/templates/datastream.rb.erb

Removing remaining references to the projecthydra GitHub organization in the code base

---

CONTRIBUTING.md

Resolves #1317 
This may be blocked until https://github.com/samvera/hydra/wiki/Dive-into-Hydra has references to Samvera replaced

Updating CONTRIBUTING with references to Samvera

---

CODE_OF_CONDUCT.md
LICENSE
README.md
SUPPORT.md

Bring project documentation in line with [maintenance templates](https://github.com/samvera-labs/maintenance)
Fixes #1349 
Fixes #1320

Maintenance templates

---

lib/active_fedora/aggregation/list_source.rb
lib/active_fedora/associations/builder/collection_association.rb
lib/active_fedora/associations/collection_association.rb
lib/active_fedora/associations/directly_contains_one_association.rb
lib/active_fedora/associations/indirectly_contains_association.rb
lib/active_fedora/associations/singular_association.rb
lib/active_fedora/attributes/property_builder.rb
lib/active_fedora/indexing/field_mapper.rb
lib/active_fedora/indexing/suffix.rb
lib/active_fedora/loadable_from_json.rb
lib/active_fedora/nested_attributes.rb
lib/active_fedora/reflection.rb
lib/active_fedora/relation/finder_methods.rb
lib/active_fedora/relation/merger.rb
lib/active_fedora/with_metadata.rb
lib/generators/active_fedora/config/solr/templates/solr/config/schema.xml

Link TODOs to recorded issues

---

lib/generators/active_fedora/config/solr/templates/solr/config/schema.xml

Use PointField Solr types rather than deprecated Trie* types

---

.travis.yml

Adding 2.6 to the build matrix for `master`.

Add and test Ruby 2.6.0

---

lib/active_fedora/version.rb

Release notes: https://github.com/samvera/active_fedora/releases/tag/untagged-fe547feba4f09791e070

Prepare release 12.1.0

---

lib/active_fedora.rb
lib/active_fedora/indexing/suffix.rb
spec/unit/active_fedora/indexing/inserter_spec.rb

Blocks progress on https://github.com/samvera/hyrax/issues/3665

Adds support for Float value indexing and ensures that Solrizer errors are defined within the global namespace

---

.circleci/config.yml

Updates the CircleCI configuration to test against Rails release 5.1.7, along with Ruby releases 2.6.3, 2.5.5, and 2.4.6

---

lib/active_fedora/version.rb

https://github.com/samvera/active_fedora/pull/1385 introduced breaking changes with release 12.2.0.  This re-releases those updates with a major version.

Releases version 13.0.0

---

.circleci/config.yml

Adding Ruby 2.7 and updating the existing Ruby and Rails releases on the CircleCI config.

---

.github_changelog_generator
CHANGELOG.md
README.md
active-fedora.gemspec

* Generate a changelog for the project
* Link from the README to the release notes in the wiki
* TODO: Add instructions for updating the changelog to the release notes

Generate a changelog

---

lib/active_fedora/file.rb
spec/unit/file_spec.rb

Co-authored-by: E. Lynette Rayle <elr37@cornell.edu>

Always rewind IO content even when the file is new.

---

lib/generators/active_fedora/config/solr/templates/solr/config/schema.xml

`StandardFilterFactory` hasn't done anything since Solr 3. Remove it for better
forward support.

remove `StandardFilterFactory`

---

lib/active_fedora/version.rb

Release 13.1.3
We need a release with the `rdf-vocab` pin.

prepare release 13.1.3

---

lib/active_fedora/version.rb

bump the release number for a minor version (adds better configurability for
client applications).

prepare release 13.2.0

---

lib/generators/active_fedora/config/solr/templates/solr/conf/schema.xml

this is (maybe?) a fix for https://github.com/samvera/hyrax/pull/4542.

add `omitNorms="true"` to solr `dateRange` as fix for Solr 8.6.3

---

lib/active_fedora/version.rb

updates the generated schema.xml to support Solr 8.6.3+

prepare release 13.2.3

---

lib/active_fedora/version.rb

Patch release for #1442 bugfix.

Bump version to prepare for release

---

.circleci/config.yml

Added test for legacy branch name check

---

CONTRIBUTING.md
README.md

Updated README and CONTRIBUTING with updated guidelines

---

lib/active_fedora/solr_service.rb
spec/unit/solr_service_spec.rb

https://github.com/rsolr/rsolr/pull/215

Handle RSolr Deprecation of read_timeout

---

.circleci/config.yml
Gemfile
lib/active_fedora/attribute_methods/read.rb
lib/active_fedora/attribute_methods/write.rb
spec/support/an_active_model.rb

This also adds nightly builds, as it's branched from #1458 
Closes #1477

Add Rails 6.1 Support

---

lib/active_fedora/version.rb

This version would include:
#1493 
#1494

Bump version for release 14.0.1

---

.circleci/config.yml
lib/active_fedora/scoping.rb

Part of https://github.com/samvera/maintenance/issues/159
Part of https://github.com/samvera/maintenance/issues/160

Test on latest ruby and rails versions

---

lib/active_fedora/version.rb

Bump version to 15.0.0 for release

---

lib/active_fedora/attribute_methods.rb
lib/active_fedora/version.rb
spec/unit/attributes_spec.rb

In preparation of merging Fedora 6 support code.

Sync 15.x-stable branch and main
